import type { editor } from 'monaco-editor';

// Each entry maps a theme ID to a Monaco IStandaloneThemeData definition.
// These are registered once via monaco.editor.defineTheme() on editor mount.

export type MonacoThemeData = editor.IStandaloneThemeData;

export const MONACO_THEMES: Record<string, { dark: MonacoThemeData; light: MonacoThemeData }> = {
  // ── NodaDB Default ─────────────────────────────────────────
  default: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '4ade80', fontStyle: 'bold' },
        { token: 'string', foreground: '86efac' },
        { token: 'number', foreground: 'a3e635' },
        { token: 'comment', foreground: '4b5563', fontStyle: 'italic' },
        { token: 'operator', foreground: '6ee7b7' },
        { token: 'identifier', foreground: 'd1fae5' },
        { token: 'type', foreground: '34d399' },
      ],
      colors: {
        'editor.background': '#121212',
        'editor.foreground': '#d1fae5',
        'editorLineNumber.foreground': '#374151',
        'editorLineNumber.activeForeground': '#4ade80',
        'editor.selectionBackground': '#4ade8030',
        'editor.lineHighlightBackground': '#1e1e1e',
        'editorCursor.foreground': '#4ade80',
        'editor.selectionHighlightBackground': '#4ade8018',
        'editorIndentGuide.background1': '#1f2937',
        'editorIndentGuide.activeBackground1': '#374151',
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#4ade8030',
        'scrollbarSlider.hoverBackground': '#4ade8060',
        'scrollbarSlider.activeBackground': '#4ade8090',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '16a34a', fontStyle: 'bold' },
        { token: 'string', foreground: '15803d' },
        { token: 'number', foreground: '65a30d' },
        { token: 'comment', foreground: '9ca3af', fontStyle: 'italic' },
        { token: 'operator', foreground: '059669' },
        { token: 'identifier', foreground: '1f2937' },
        { token: 'type', foreground: '047857' },
      ],
      colors: {
        'editor.background': '#f8fafb',
        'editor.foreground': '#1f2937',
        'editorLineNumber.foreground': '#9ca3af',
        'editorLineNumber.activeForeground': '#16a34a',
        'editor.selectionBackground': '#16a34a28',
        'editor.lineHighlightBackground': '#f0fdf4',
        'editorCursor.foreground': '#16a34a',
        'scrollbarSlider.background': '#16a34a20',
        'scrollbarSlider.hoverBackground': '#16a34a40',
      },
    },
  },

  // ── One Dark Pro ───────────────────────────────────────────
  'one-dark-pro': {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'c678dd', fontStyle: 'bold' },
        { token: 'string', foreground: '98c379' },
        { token: 'number', foreground: 'd19a66' },
        { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
        { token: 'operator', foreground: '56b6c2' },
        { token: 'identifier', foreground: 'e06c75' },
        { token: 'type', foreground: 'e5c07b' },
      ],
      colors: {
        'editor.background': '#21252b',
        'editor.foreground': '#abb2bf',
        'editorLineNumber.foreground': '#495162',
        'editorLineNumber.activeForeground': '#abb2bf',
        'editor.selectionBackground': '#3d4350',
        'editor.lineHighlightBackground': '#2c313a',
        'editorCursor.foreground': '#528bff',
        'scrollbarSlider.background': '#4b535d50',
        'scrollbarSlider.hoverBackground': '#4b535d80',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '4078f2', fontStyle: 'bold' },
        { token: 'string', foreground: '50a14f' },
        { token: 'number', foreground: 'c18401' },
        { token: 'comment', foreground: 'a0a1a7', fontStyle: 'italic' },
        { token: 'operator', foreground: '0184bc' },
        { token: 'identifier', foreground: 'e45649' },
        { token: 'type', foreground: '986801' },
      ],
      colors: {
        'editor.background': '#fafafa',
        'editor.foreground': '#383a42',
        'editorLineNumber.foreground': '#9d9d9f',
        'editorLineNumber.activeForeground': '#4078f2',
        'editor.selectionBackground': '#4078f228',
        'editor.lineHighlightBackground': '#f0f0f0',
        'editorCursor.foreground': '#4078f2',
      },
    },
  },

  // ── Nord ───────────────────────────────────────────────────
  nord: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '81a1c1', fontStyle: 'bold' },
        { token: 'string', foreground: 'a3be8c' },
        { token: 'number', foreground: 'b48ead' },
        { token: 'comment', foreground: '4c566a', fontStyle: 'italic' },
        { token: 'operator', foreground: '88c0d0' },
        { token: 'identifier', foreground: 'eceff4' },
        { token: 'type', foreground: '8fbcbb' },
      ],
      colors: {
        'editor.background': '#2e3440',
        'editor.foreground': '#d8dee9',
        'editorLineNumber.foreground': '#4c566a',
        'editorLineNumber.activeForeground': '#88c0d0',
        'editor.selectionBackground': '#4c566a80',
        'editor.lineHighlightBackground': '#3b4252',
        'editorCursor.foreground': '#88c0d0',
        'scrollbarSlider.background': '#4c566a50',
        'scrollbarSlider.hoverBackground': '#4c566a80',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '5e81ac', fontStyle: 'bold' },
        { token: 'string', foreground: '4f7a28' },
        { token: 'number', foreground: 'b48ead' },
        { token: 'comment', foreground: '9aa1b1', fontStyle: 'italic' },
        { token: 'operator', foreground: '5e81ac' },
        { token: 'identifier', foreground: '2e3440' },
        { token: 'type', foreground: '3b7c87' },
      ],
      colors: {
        'editor.background': '#f0f4f8',
        'editor.foreground': '#2e3440',
        'editorLineNumber.foreground': '#9aa1b1',
        'editorLineNumber.activeForeground': '#5e81ac',
        'editor.selectionBackground': '#5e81ac28',
        'editor.lineHighlightBackground': '#e5eaf2',
        'editorCursor.foreground': '#5e81ac',
      },
    },
  },

  // ── Claude ─────────────────────────────────────────────────
  claude: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'd4715a', fontStyle: 'bold' },
        { token: 'string', foreground: 'c8956a' },
        { token: 'number', foreground: 'e8a87c' },
        { token: 'comment', foreground: '5a4a3a', fontStyle: 'italic' },
        { token: 'operator', foreground: 'bf8b6e' },
        { token: 'identifier', foreground: 'e8d5c0' },
        { token: 'type', foreground: 'cc8866' },
      ],
      colors: {
        'editor.background': '#1a1512',
        'editor.foreground': '#e8d5c0',
        'editorLineNumber.foreground': '#5a4a3a',
        'editorLineNumber.activeForeground': '#d4715a',
        'editor.selectionBackground': '#d4715a28',
        'editor.lineHighlightBackground': '#231e18',
        'editorCursor.foreground': '#d4715a',
        'scrollbarSlider.background': '#5a4a3a50',
        'scrollbarSlider.hoverBackground': '#5a4a3a80',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'b85c43', fontStyle: 'bold' },
        { token: 'string', foreground: '9b6e3e' },
        { token: 'number', foreground: 'c47a3a' },
        { token: 'comment', foreground: 'b8a090', fontStyle: 'italic' },
        { token: 'operator', foreground: 'a0684e' },
        { token: 'identifier', foreground: '3a2818' },
        { token: 'type', foreground: 'a05438' },
      ],
      colors: {
        'editor.background': '#fdf8f4',
        'editor.foreground': '#3a2818',
        'editorLineNumber.foreground': '#b8a090',
        'editorLineNumber.activeForeground': '#b85c43',
        'editor.selectionBackground': '#b85c4328',
        'editor.lineHighlightBackground': '#f5ede4',
        'editorCursor.foreground': '#b85c43',
      },
    },
  },

  // ── Tokyo Night ────────────────────────────────────────────
  'tokyo-night': {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'bb9af7', fontStyle: 'bold' },
        { token: 'string', foreground: '9ece6a' },
        { token: 'number', foreground: 'ff9e64' },
        { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
        { token: 'operator', foreground: '7dcfff' },
        { token: 'identifier', foreground: 'c0caf5' },
        { token: 'type', foreground: '2ac3de' },
      ],
      colors: {
        'editor.background': '#1a1b2e',
        'editor.foreground': '#c0caf5',
        'editorLineNumber.foreground': '#3b4261',
        'editorLineNumber.activeForeground': '#7aa2f7',
        'editor.selectionBackground': '#283457',
        'editor.lineHighlightBackground': '#1f2335',
        'editorCursor.foreground': '#7aa2f7',
        'scrollbarSlider.background': '#3b426150',
        'scrollbarSlider.hoverBackground': '#3b426180',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '5a7cde', fontStyle: 'bold' },
        { token: 'string', foreground: '485e30' },
        { token: 'number', foreground: 'b15c00' },
        { token: 'comment', foreground: '9699a3', fontStyle: 'italic' },
        { token: 'operator', foreground: '166775' },
        { token: 'identifier', foreground: '343b58' },
        { token: 'type', foreground: '0f4b6e' },
      ],
      colors: {
        'editor.background': '#d5d6db',
        'editor.foreground': '#343b58',
        'editorLineNumber.foreground': '#9699a3',
        'editorLineNumber.activeForeground': '#5a7cde',
        'editor.selectionBackground': '#5a7cde28',
        'editor.lineHighlightBackground': '#c9cad0',
        'editorCursor.foreground': '#5a7cde',
      },
    },
  },

  // ── Catppuccin ─────────────────────────────────────────────
  catppuccin: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'cba6f7', fontStyle: 'bold' },
        { token: 'string', foreground: 'a6e3a1' },
        { token: 'number', foreground: 'fab387' },
        { token: 'comment', foreground: '585b70', fontStyle: 'italic' },
        { token: 'operator', foreground: '89dceb' },
        { token: 'identifier', foreground: 'cdd6f4' },
        { token: 'type', foreground: '89b4fa' },
      ],
      colors: {
        'editor.background': '#1e1e2e',
        'editor.foreground': '#cdd6f4',
        'editorLineNumber.foreground': '#45475a',
        'editorLineNumber.activeForeground': '#cba6f7',
        'editor.selectionBackground': '#585b7040',
        'editor.lineHighlightBackground': '#181825',
        'editorCursor.foreground': '#f5c2e7',
        'scrollbarSlider.background': '#45475a50',
        'scrollbarSlider.hoverBackground': '#45475a80',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '8839ef', fontStyle: 'bold' },
        { token: 'string', foreground: '40a02b' },
        { token: 'number', foreground: 'fe640b' },
        { token: 'comment', foreground: '8c8fa1', fontStyle: 'italic' },
        { token: 'operator', foreground: '209fb5' },
        { token: 'identifier', foreground: '4c4f69' },
        { token: 'type', foreground: '1e66f5' },
      ],
      colors: {
        'editor.background': '#eff1f5',
        'editor.foreground': '#4c4f69',
        'editorLineNumber.foreground': '#8c8fa1',
        'editorLineNumber.activeForeground': '#8839ef',
        'editor.selectionBackground': '#8839ef28',
        'editor.lineHighlightBackground': '#e6e9f0',
        'editorCursor.foreground': '#dc8a78',
      },
    },
  },

  // ── Dracula ────────────────────────────────────────────────
  dracula: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'ff79c6', fontStyle: 'bold' },
        { token: 'string', foreground: 'f1fa8c' },
        { token: 'number', foreground: 'bd93f9' },
        { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
        { token: 'operator', foreground: 'ff79c6' },
        { token: 'identifier', foreground: 'f8f8f2' },
        { token: 'type', foreground: '8be9fd' },
      ],
      colors: {
        'editor.background': '#282a36',
        'editor.foreground': '#f8f8f2',
        'editorLineNumber.foreground': '#6272a4',
        'editorLineNumber.activeForeground': '#f8f8f2',
        'editor.selectionBackground': '#44475a',
        'editor.lineHighlightBackground': '#44475a50',
        'editorCursor.foreground': '#f8f8f2',
        'scrollbarSlider.background': '#44475a80',
        'scrollbarSlider.hoverBackground': '#44475aaa',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '6272a4', fontStyle: 'bold' },
        { token: 'string', foreground: 'f1fa8c' },
        { token: 'number', foreground: 'bd93f9' },
        { token: 'comment', foreground: '9ba5c9', fontStyle: 'italic' },
        { token: 'operator', foreground: 'ff79c6' },
        { token: 'identifier', foreground: '282a36' },
        { token: 'type', foreground: '8be9fd' },
      ],
      colors: {
        'editor.background': '#f8f8f8',
        'editor.foreground': '#282a36',
        'editorLineNumber.foreground': '#9ba5c9',
        'editorLineNumber.activeForeground': '#6272a4',
        'editor.selectionBackground': '#6272a428',
        'editor.lineHighlightBackground': '#ededf0',
        'editorCursor.foreground': '#ff79c6',
      },
    },
  },

  // ── Gruvbox ────────────────────────────────────────────────
  gruvbox: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'fb4934', fontStyle: 'bold' },
        { token: 'string', foreground: 'b8bb26' },
        { token: 'number', foreground: 'd3869b' },
        { token: 'comment', foreground: '665c54', fontStyle: 'italic' },
        { token: 'operator', foreground: '8ec07c' },
        { token: 'identifier', foreground: 'ebdbb2' },
        { token: 'type', foreground: 'fabd2f' },
      ],
      colors: {
        'editor.background': '#282828',
        'editor.foreground': '#ebdbb2',
        'editorLineNumber.foreground': '#504945',
        'editorLineNumber.activeForeground': '#fabd2f',
        'editor.selectionBackground': '#504945',
        'editor.lineHighlightBackground': '#32302f',
        'editorCursor.foreground': '#fabd2f',
        'scrollbarSlider.background': '#50494550',
        'scrollbarSlider.hoverBackground': '#50494580',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '9d0006', fontStyle: 'bold' },
        { token: 'string', foreground: '79740e' },
        { token: 'number', foreground: '8f3f71' },
        { token: 'comment', foreground: 'a89984', fontStyle: 'italic' },
        { token: 'operator', foreground: '427b58' },
        { token: 'identifier', foreground: '3c3836' },
        { token: 'type', foreground: 'b57614' },
      ],
      colors: {
        'editor.background': '#fbf1c7',
        'editor.foreground': '#3c3836',
        'editorLineNumber.foreground': '#a89984',
        'editorLineNumber.activeForeground': '#b57614',
        'editor.selectionBackground': '#b5761428',
        'editor.lineHighlightBackground': '#f2e5bc',
        'editorCursor.foreground': '#b57614',
      },
    },
  },

  // ── Rosé Pine ──────────────────────────────────────────────
  'rose-pine': {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '31748f', fontStyle: 'bold' },
        { token: 'string', foreground: '9ccfd8' },
        { token: 'number', foreground: 'eb6f92' },
        { token: 'comment', foreground: '524f67', fontStyle: 'italic' },
        { token: 'operator', foreground: 'ebbcba' },
        { token: 'identifier', foreground: 'e0def4' },
        { token: 'type', foreground: 'c4a7e7' },
      ],
      colors: {
        'editor.background': '#191724',
        'editor.foreground': '#e0def4',
        'editorLineNumber.foreground': '#393552',
        'editorLineNumber.activeForeground': '#ebbcba',
        'editor.selectionBackground': '#403d5280',
        'editor.lineHighlightBackground': '#1f1d2e',
        'editorCursor.foreground': '#eb6f92',
        'scrollbarSlider.background': '#39355250',
        'scrollbarSlider.hoverBackground': '#39355280',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '286983', fontStyle: 'bold' },
        { token: 'string', foreground: '56949f' },
        { token: 'number', foreground: 'b4637a' },
        { token: 'comment', foreground: '9893a5', fontStyle: 'italic' },
        { token: 'operator', foreground: 'd7827a' },
        { token: 'identifier', foreground: '575279' },
        { token: 'type', foreground: '907aa9' },
      ],
      colors: {
        'editor.background': '#faf4ed',
        'editor.foreground': '#575279',
        'editorLineNumber.foreground': '#9893a5',
        'editorLineNumber.activeForeground': '#d7827a',
        'editor.selectionBackground': '#d7827a28',
        'editor.lineHighlightBackground': '#f2e9de',
        'editorCursor.foreground': '#b4637a',
      },
    },
  },

  // ── Solarized ──────────────────────────────────────────────
  solarized: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '859900', fontStyle: 'bold' },
        { token: 'string', foreground: '2aa198' },
        { token: 'number', foreground: 'd33682' },
        { token: 'comment', foreground: '586e75', fontStyle: 'italic' },
        { token: 'operator', foreground: '268bd2' },
        { token: 'identifier', foreground: '839496' },
        { token: 'type', foreground: 'b58900' },
      ],
      colors: {
        'editor.background': '#002b36',
        'editor.foreground': '#839496',
        'editorLineNumber.foreground': '#073642',
        'editorLineNumber.activeForeground': '#2aa198',
        'editor.selectionBackground': '#073642',
        'editor.lineHighlightBackground': '#073642',
        'editorCursor.foreground': '#839496',
        'scrollbarSlider.background': '#07364250',
        'scrollbarSlider.hoverBackground': '#07364280',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '859900', fontStyle: 'bold' },
        { token: 'string', foreground: '2aa198' },
        { token: 'number', foreground: 'd33682' },
        { token: 'comment', foreground: '93a1a1', fontStyle: 'italic' },
        { token: 'operator', foreground: '268bd2' },
        { token: 'identifier', foreground: '657b83' },
        { token: 'type', foreground: 'b58900' },
      ],
      colors: {
        'editor.background': '#fdf6e3',
        'editor.foreground': '#657b83',
        'editorLineNumber.foreground': '#93a1a1',
        'editorLineNumber.activeForeground': '#2aa198',
        'editor.selectionBackground': '#eee8d5',
        'editor.lineHighlightBackground': '#eee8d5',
        'editorCursor.foreground': '#657b83',
      },
    },
  },

  // ── Monochrome ─────────────────────────────────────────────
  monochrome: {
    dark: {
      base: 'vs-dark',
      inherit: false,
      rules: [
        { token: '', foreground: 'e8e8e8' },
        { token: 'keyword', foreground: 'ffffff', fontStyle: 'bold' },
        { token: 'string', foreground: 'c0c0c0' },
        { token: 'number', foreground: 'd8d8d8' },
        { token: 'comment', foreground: '555555', fontStyle: 'italic' },
        { token: 'operator', foreground: 'aaaaaa' },
        { token: 'identifier', foreground: 'e0e0e0' },
        { token: 'type', foreground: 'bbbbbb', fontStyle: 'bold' },
      ],
      colors: {
        'editor.background': '#000000',
        'editor.foreground': '#e0e0e0',
        'editorLineNumber.foreground': '#333333',
        'editorLineNumber.activeForeground': '#888888',
        'editor.selectionBackground': '#333333',
        'editor.lineHighlightBackground': '#111111',
        'editorCursor.foreground': '#ffffff',
        'editorIndentGuide.background1': '#222222',
        'editorIndentGuide.activeBackground1': '#444444',
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#33333350',
        'scrollbarSlider.hoverBackground': '#33333380',
        'scrollbarSlider.activeBackground': '#555555',
      },
    },
    light: {
      base: 'vs',
      inherit: false,
      rules: [
        { token: '', foreground: '111111' },
        { token: 'keyword', foreground: '000000', fontStyle: 'bold' },
        { token: 'string', foreground: '444444' },
        { token: 'number', foreground: '333333' },
        { token: 'comment', foreground: 'aaaaaa', fontStyle: 'italic' },
        { token: 'operator', foreground: '555555' },
        { token: 'identifier', foreground: '222222' },
        { token: 'type', foreground: '333333', fontStyle: 'bold' },
      ],
      colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#111111',
        'editorLineNumber.foreground': '#cccccc',
        'editorLineNumber.activeForeground': '#666666',
        'editor.selectionBackground': '#dddddd',
        'editor.lineHighlightBackground': '#f5f5f5',
        'editorCursor.foreground': '#000000',
        'editorIndentGuide.background1': '#eeeeee',
        'editorIndentGuide.activeBackground1': '#cccccc',
        'scrollbarSlider.background': '#cccccc50',
        'scrollbarSlider.hoverBackground': '#cccccc80',
      },
    },
  },

  // ── Material ───────────────────────────────────────────────
  material: {
    dark: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: 'c792ea', fontStyle: 'bold' },
        { token: 'string', foreground: 'c3e88d' },
        { token: 'number', foreground: 'f78c6c' },
        { token: 'comment', foreground: '546e7a', fontStyle: 'italic' },
        { token: 'operator', foreground: '89ddff' },
        { token: 'identifier', foreground: 'eeffff' },
        { token: 'type', foreground: 'ffcb6b' },
      ],
      colors: {
        'editor.background': '#263238',
        'editor.foreground': '#eeffff',
        'editorLineNumber.foreground': '#37474f',
        'editorLineNumber.activeForeground': '#89ddff',
        'editor.selectionBackground': '#80cbc420',
        'editor.lineHighlightBackground': '#00000040',
        'editorCursor.foreground': '#ffcc00',
        'editorIndentGuide.background1': '#37474f',
        'editorIndentGuide.activeBackground1': '#546e7a',
        'scrollbar.shadow': '#00000000',
        'scrollbarSlider.background': '#37474f50',
        'scrollbarSlider.hoverBackground': '#37474f80',
        'scrollbarSlider.activeBackground': '#546e7a',
      },
    },
    light: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: 'keyword', foreground: '7c4dff', fontStyle: 'bold' },
        { token: 'string', foreground: '2e7d32' },
        { token: 'number', foreground: 'f57c00' },
        { token: 'comment', foreground: '9e9e9e', fontStyle: 'italic' },
        { token: 'operator', foreground: '0288d1' },
        { token: 'identifier', foreground: '263238' },
        { token: 'type', foreground: 'f57f17' },
      ],
      colors: {
        'editor.background': '#fafafa',
        'editor.foreground': '#263238',
        'editorLineNumber.foreground': '#b0bec5',
        'editorLineNumber.activeForeground': '#7c4dff',
        'editor.selectionBackground': '#7c4dff18',
        'editor.lineHighlightBackground': '#f5f5f5',
        'editorCursor.foreground': '#7c4dff',
        'editorIndentGuide.background1': '#eeeeee',
        'editorIndentGuide.activeBackground1': '#e0e0e0',
        'scrollbarSlider.background': '#b0bec520',
        'scrollbarSlider.hoverBackground': '#b0bec540',
      },
    },
  },
};

/**
 * Returns the Monaco theme ID string for a given app theme ID and appearance mode.
 * The theme ID is used both to register (defineTheme) and set (setTheme).
 */
export function getMonacoThemeId(colorTheme: string, isDark: boolean): string {
  return `noda-${colorTheme}-${isDark ? 'dark' : 'light'}`;
}
